name: Static Resource Checking
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  static-resource-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4

      - name: Check Static Resources
        run: |
          declare -A RESOURCES
          RESOURCES["src/main/resources/html/ScanSummaryInit.html"]="https://raw.githubusercontent.com/snyk/snyk-ls/refs/heads/main/shared_ide_resources/ui/html/ScanSummaryInit.html"
          for key in ${!RESOURCES[@]}; do
            CANDIDATE=$(sha1sum $key | awk {'print $1'})
            REFERENCE=$(curl ${RESOURCES[$key]} | sha1sum | awk {'print $1'})
            echo "Candidate file $key has sha1sum $CANDIDATE"
            echo "Reference file ${RESOURCES[$key]} has sha1sum $REFERENCE"
            [[ $CANDIDATE == $REFERENCE ]]
          done

